services:
  postgres:
    container_name: gestao_cursos_postgres
    image: postgres
    ports:
      - 6432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_cursos
